name: Bug report
description: Report an error or unexpected behavior
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report an issue! We're glad to have you involved with action-format.

        **Before reporting, please make sure to search through [existing issues](https://github.com/MatthewMckee4/action-format/issues?q=is:issue+is:open+label:bug) (including [closed](https://github.com/MatthewMckee4/action-format/issues?q=is:issue%20state:closed%20label:bug)).**

  - type: textarea
    attributes:
      label: Summary
      description: |
        A clear and concise description of the bug, including a minimal reproducible example.

        Be sure to include the command you invoked (e.g., `action-format --diff`)

    validations:
      required: true
